version: '3.8'

networks:
  polycode-dev:

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  nats:
    image: nats:latest
    networks:
      - polycode-dev
    ports:
      - "4222:4222"   # NATS client port
      - "8222:8222"   # NATS monitoring port (optional)
    restart: unless-stopped

  next-env:
    depends_on:
      - dynamodb
      - s3
      - nats
    image: 537413656254.dkr.ecr.us-east-1.amazonaws.com/cloudimpl/xxx/next-env:latest
    networks:
      - polycode-dev
    pull_policy: always
    volumes:
      - ./.runtime:/tmp
    command: ["/var/task/bootstrap-fargate.sh"]
    restart: unless-stopped
    environment:
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NATS_HOST: "nats:4222"
      DIRECT_ACCESS: "true"
      polycode_DEV_MODE: "true"
      polycode_ORG_ID: ${polycode_ORG_ID}
      polycode_ENV_ID: ${polycode_ENV_ID}
      polycode_APP_NAME: "next-env"
      polycode_SERVICE_IDS: "auth-service,param-service,file-service"
      polycode_RUNTIME: "dev"

  next-agent-runtime:
    depends_on:
      - dynamodb
      - s3
      - nats
    image: 485496110001.dkr.ecr.us-east-1.amazonaws.com/485496110001/h7npshowhzdc5d/app-u6fj1h32637699:latest
    networks:
      - polycode-dev
    pull_policy: always
    volumes:
      - ./.runtime:/tmp
    command: ["/var/task/bootstrap-fargate.sh"]
    restart: unless-stopped
    environment:
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NATS_HOST: "nats:4222"
      DIRECT_ACCESS: "true"
      polycode_DEV_MODE: "true"
      polycode_ORG_ID: ${polycode_ORG_ID}
      polycode_ENV_ID: ${polycode_ENV_ID}
      polycode_APP_NAME: "next-agent-runtime"
      polycode_SERVICE_IDS: "agent-service"
      polycode_RUNTIME: "dev"
      polycode_ENV_EXTRACTOR: "shared agent"

  next-ai-gateway:
    depends_on:
      - dynamodb
      - s3
      - nats
    image: 485496110001.dkr.ecr.us-east-1.amazonaws.com/485496110001/h7npshowhzdc5d/app-xxor0ebrq8q2wg:latest
    networks:
      - polycode-dev
    pull_policy: always
    volumes:
      - ./.runtime:/tmp
    command: ["/var/task/bootstrap-fargate.sh"]
    restart: unless-stopped
    environment:
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NATS_HOST: "nats:4222"
      DIRECT_ACCESS: "true"
      polycode_DEV_MODE: "true"
      polycode_ORG_ID: ${polycode_ORG_ID}
      polycode_ENV_ID: ${polycode_ENV_ID}
      polycode_APP_NAME: "next-ai-gw"
      polycode_SERVICE_IDS: "ai-gateway-service"
      polycode_RUNTIME: "dev"
