version: '3.8'

networks:
  polycode-dev:
    name: polycode-dev

services:
  dynamodb:
    image: amazon/dynamodb-local
    networks:
      - polycode-dev
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./data/dynamodb-local:/data

  s3:
    image: minio/minio
    networks:
      - polycode-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CORS_ALLOW_ORIGIN: "*"
      MINIO_CORS_ALLOW_METHODS: "GET,PUT,HEAD"
      MINIO_CORS_ALLOW_HEADERS: "*"
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

  nats:
    image: nats:latest
    networks:
      - polycode-dev
    ports:
      - "4222:4222"   # NATS client port
      - "8222:8222"   # NATS monitoring port (optional)
    restart: unless-stopped
