version: '3.8'

networks:
  polycode-dev:
    external: true

services:
  next-env:
    image: 537413656254.dkr.ecr.us-east-1.amazonaws.com/cloudimpl/xxx/next-env:latest
    networks:
      - polycode-dev
    pull_policy: always
    volumes:
      - ./runtime:/tmp
    command: ["/var/task/bootstrap-fargate.sh"]
    restart: unless-stopped
    environment:
      polycode_DEV_MODE: "true"
      polycode_ORG_ID: "xxx"
      polycode_ENV_ID: ${ENVIRONMENT_ID}
      polycode_APP_NAME: "next-env"
      polycode_SERVICE_IDS: "auth-service,param-service,file-service"

  next-agent-runtime:
    image: 485496110001.dkr.ecr.us-east-1.amazonaws.com/485496110001/h7npshowhzdc5d/app-u6fj1h32637699:latest
    networks:
      - polycode-dev
    pull_policy: always
    volumes:
      - ./runtime:/tmp
    command: ["/var/task/bootstrap-fargate.sh"]
    restart: unless-stopped
    environment:
      polycode_DEV_MODE: "true"
      polycode_ORG_ID: "xxx"
      polycode_ENV_ID: ${ENVIRONMENT_ID}
      polycode_APP_NAME: "next-agent-runtime"
      polycode_SERVICE_IDS: "agent-service"
      polycode_ENV_EXTRACTOR: "shared agent"

  next-ai-gateway:
    image: 485496110001.dkr.ecr.us-east-1.amazonaws.com/485496110001/h7npshowhzdc5d/app-xxor0ebrq8q2wg:latest
    networks:
      - polycode-dev
    pull_policy: always
    volumes:
      - ./runtime:/tmp
    command: ["/var/task/bootstrap-fargate.sh"]
    restart: unless-stopped
    environment:
      polycode_DEV_MODE: "true"
      polycode_ORG_ID: "xxx"
      polycode_ENV_ID: ${ENVIRONMENT_ID}
      polycode_APP_NAME: "next-ai-gw"
      polycode_SERVICE_IDS: "ai-gateway-service"
